import { Vehicle } from './types';

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'mercedes-benz-e300-2017-black',
    make: 'Mercedes-Benz',
    model: 'E300',
    year: 2017,
    price: 26000000,
    mileage: 45000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/gqVm8Vk/IMG-20260728-WA0028.jpg',
      'https://i.ibb.co/xSRC0fdx/IMG-20260728-WA0030.jpg',
      'https://i.ibb.co/SLyYjtd/IMG-20260728-WA0032.jpg',
      'https://i.ibb.co/67bXyBCX/IMG-20260728-WA0034.jpg',
      'https://i.ibb.co/v6HKh71B/IMG-20260728-WA0036.jpg'
    ],
    description: "✨ 2017 Mercedes-Benz E300 (4-door Luxury Sedan) ✨\n💎 Condition: Extremely Clean Used (as advertised) | 📄 Customs Duty Paid 📜 | 🖤 Obsidian Black Exterior\n\nVehicle Overview:\nThe 2017 Mercedes-Benz E300 represents the benchmark of executive luxury sedans. Powered by a responsive 2.0L Turbocharged Inline-4 engine paired with a 9-Speed Automatic 9G-TRONIC transmission delivering 241 hp, this unit is extremely clean, well-maintained, and fully duty paid.\n\nKey Performance & Luxury Features:\n⚙️ 2.0L Turbocharged Inline-4 (241 hp / 273 lb-ft Torque)\n🕹️ 9-Speed Automatic Transmission (9G-TRONIC)\n💡 LED Intelligent Headlamps & Daytime Running Lights\n🔑 Keyless Start & Smart Access\n🛋️ Premium Leather Interior with Power Front Seats & Memory\n❄️ Dual-Zone Automatic Climate Control\n🏎️ Multifunction Steering Wheel & Cruise Control\n📱 Large High-Resolution Infotainment Display with Bluetooth\n📷 Reverse Camera with Front & Rear Parking Sensors\n🛞 Executive Alloy Wheels\n🛡️ Collision Prevention Assist, Attention Assist, ESP, Traction Control & Multiple Airbags",
    engine: '2.0L Turbocharged Inline-4 (241 hp)',
    color: 'Black',
    condition: 'Extremely Clean',
    isFeatured: true
  },
  {
    id: 'toyota-hilux-2024-white',
    make: 'Toyota',
    model: 'Hilux',
    year: 2024,
    price: 59000000,
    mileage: 5000,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    bodyType: 'Truck',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/TNDxQB3/IMG-20260728-WA0026.jpg',
      'https://i.ibb.co/DfP9xWTp/IMG-20260728-WA0020.jpg',
      'https://i.ibb.co/nsZm53b8/IMG-20260728-WA0024.jpg',
      'https://i.ibb.co/m5Hdg2S1/IMG-20260728-WA0022.jpg',
      'https://i.ibb.co/v4Lh1pfV/IMG-20260728-WA0014.jpg'
    ],
    description: "✨ 2024 Toyota Hilux (Registered, Like New) ✨\n🌍 Registered, Bought Brand New in 2024 | 📄 Duty Paid 📜 | 💎 Like New Condition\n\nVehicle Overview:\nThe 2024 Toyota Hilux is one of the most dependable pickup trucks on the market, renowned for its rugged durability, exceptional performance, and outstanding reliability. This unit was purchased brand new last year, is Nigerian registered, and remains in like-new condition with genuine duty paid. It is ideal for both commercial operations and personal use.\n\nKey Features:\n⚙️ 2.8L Turbo Diesel Engine\n🏎️ Automatic Transmission & 4WD Capability\n🔑 Smart Key / Keyless Entry & Push-Button Start\n📱 Touchscreen Infotainment System with Apple CarPlay & Android Auto\n📶 Bluetooth Connectivity\n📷 Reverse Camera & Rear Parking Sensors\n🏎️ Multifunction Steering Wheel & Cruise Control\n❄️ Automatic Climate Control\n💡 LED Headlights, Daytime Running Lights & Fog Lights\n🛞 Alloy Wheels, Side Steps, Bed Cover (Tonneau Cover) & Sports Bar\n⚡ Power Windows & Mirrors\n🛡️ Multiple Airbags, ABS, Vehicle Stability Control (VSC) & Traction Control",
    engine: '2.8L Turbo Diesel',
    color: 'White',
    condition: 'Like New',
    isFeatured: true
  },
  {
    id: 'honda-crv-limited-edition-2021-white',
    make: 'Honda',
    model: 'CR-V Limited Edition',
    year: 2021,
    price: 25000000,
    mileage: 22000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/6c9x4xK9/IMG-20260728-WA0011.jpg',
      'https://i.ibb.co/M5fgMvt4/IMG-20260728-WA0012.jpg',
      'https://i.ibb.co/qMsZnCFP/IMG-20260728-WA0010.jpg',
      'https://i.ibb.co/XZQqJ3NY/IMG-20260728-WA0016.jpg',
      'https://i.ibb.co/mFh4cKD9/IMG-20260728-WA0018.jpg'
    ],
    description: "✨ 2021 Honda CR-V Limited Edition (Slightly Used, Unregistered) ✨\n🌍 Slightly Used, Unregistered | 📄 Original Papers Available 📜 | 💎 Excellent Condition\n\nVehicle Overview:\nThe 2021 Honda CR-V Limited Edition is a premium compact SUV that blends modern styling, exceptional comfort, advanced safety, and fuel-efficient performance. This unregistered Nigerian unit is in excellent condition and comes with sought-after features including keyless entry and a panoramic sunroof, making it an ideal SUV for families and professionals alike.\n\nKey Features:\n⚙️ 1.5L Turbocharged Petrol Engine\n🏎️ Automatic Transmission (CVT) & Front-Wheel Drive (FWD)\n🌟 Limited Edition Trim\n🔑 Smart Key / Keyless Entry & Push-Button Start\n🌅 Panoramic Sunroof\n💡 LED Headlights, Daytime Running Lights & LED Fog Lights\n🛞 Alloy Wheels\n📷 Reverse Camera & Front & Rear Parking Sensors\n📱 Touchscreen Infotainment System with Apple CarPlay, Android Auto & Bluetooth\n⚡ USB Charging Ports & Power Tailgate\n❄️ Dual-Zone Automatic Climate Control\n🏎️ Multifunction Steering Wheel & Cruise Control\n🅿️ Electric Parking Brake with Auto Hold\n🪑 Premium Interior Finish\n🛡️ Multiple Airbags, ABS, Vehicle Stability Assist (VSA) & Traction Control",
    engine: '1.5L Turbocharged Petrol',
    color: 'White',
    condition: 'Slightly Used',
    isFeatured: true
  },
  {
    id: 'toyota-tacoma-2017-full-option',
    make: 'Toyota',
    model: 'Tacoma Full Option',
    year: 2017,
    price: 43500000,
    mileage: 48000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Truck',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/qMcQ5ckY/IMG-20260728-WA0003.jpg'
    ],
    description: "✨ 2017 Toyota Tacoma (Direct Belgium) – Full Option ✨\n🌍 Direct Belgium | 📄 Valid Duty (Expires April 2026) 📜 | 💎 Accident-Free\n\nVehicle Overview:\nThe 2017 Toyota Tacoma is a rugged midsize pickup built for both everyday driving and demanding off-road adventures. This accident-free, Direct Belgium unit comes in full-option specification with a powerful engine, premium features, and a well-maintained exterior and interior. With duty valid until April 2026, it's ready for immediate use.\n\nKey Features:\n⚙️ 3.5L V6 Petrol Engine\n🏎️ 6-Speed Automatic Transmission\n🛣️ 4WD (Four-Wheel Drive)\n🌟 Full Option Package\n🏎️ TRD-Style Front Grille & Hood Scoop\n💡 LED Daytime Running Lights & Fog Lights\n🛞 Alloy Wheels with All-Terrain Tires & Side Steps\n📱 Touchscreen Infotainment System with Bluetooth, Apple CarPlay & Android Auto\n📷 Reverse Camera & Push-Button Start / Smart Key Entry\n🏎️ Cruise Control & Dual-Zone Automatic Climate Control\n🪑 Leather/Fabric Premium Interior & Multifunction Steering Wheel\n🛡️ Multiple Airbags, ABS, Traction Control, Vehicle Stability Control, Hill Start Assist & Trailer Sway Control",
    engine: '3.5L V6 Petrol',
    color: 'Orange',
    condition: 'Direct Belgium',
    isFeatured: true
  },
  {
    id: 'toyota-camry-se-2015-silver',
    make: 'Toyota',
    model: 'Camry SE',
    year: 2015,
    price: 14300000,
    mileage: 58000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/tMr2rYx4/IMG-20260723-WA0028.jpg'
    ],
    description: "✨ 2015 Toyota Camry SE ✨\n🌍 Mint Foreign Used | 📄 Genuine Duty Paid 📜 | 🏎️ Sport Trim\n\nThe 2015 Toyota Camry SE offers a perfect combination of sporty styling, reliability, fuel efficiency, and comfort. This foreign-used unit is in mint condition with a clean interior, factory reverse camera, and an untampered engine and transmission, making it an excellent choice for personal or family use.\n\nKey Features:\n⚙️ 2.5L 4-Cylinder DOHC Engine\n🏎️ Automatic Transmission & Front-Wheel Drive (FWD)\n📷 Factory Reverse Camera & Sport (SE) Body Kit\n🛞 Alloy Wheels & Fabric Sport Seats\n🎡 Multifunction Steering Wheel & Cruise Control\n🎵 Bluetooth, USB & AUX Audio Input\n❄️ Air Conditioning & Keyless Entry\n⚡ Power Windows & Mirrors & Fog Lights\n🛡️ ABS Braking System, VSC & Driver/Passenger Airbags\n\nCondition Report:\n✅ Mint Foreign Used\n✅ Clean and well-kept interior\n✅ Untampered engine & smooth automatic transmission\n✅ Excellent suspension & neat exterior paintwork\n✅ Genuine duty paid & ready to drive",
    engine: '2.5L 4-Cylinder Petrol',
    color: 'Silver',
    condition: 'Foreign Used',
    isFeatured: true
  },
  {
    id: 'mercedes-benz-cla-250-2014',
    make: 'Mercedes-Benz',
    model: 'CLA 250',
    year: 2014,
    price: 19000000,
    mileage: 62000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/cS42nbXX/9ab7afef35ae48c88563da945ef8ad76.jpg'
    ],
    description: "✨ 2014 Mercedes-Benz CLA 250 ✨\n🌍 Foreign Used | 📄 Custom Duty Paid | 🌟 Excellent Luxury Condition\n\nThe 2014 Mercedes-Benz CLA 250 is a stylish luxury compact sedan that combines sporty performance with premium comfort and advanced technology. Featuring a sleek coupe-inspired design, turbocharged power, and a refined interior, this foreign-used unit offers an excellent blend of elegance and driving excitement.\n\nKey Features:\n⚙️ 2.0L Turbocharged Inline-4 Engine\n🏎️ 7-Speed Dual-Clutch Automatic Transmission (7G-DCT)\n🔑 Push-Button Start & Keyless Entry\n🪑 Leather Upholstery with Memory Power Front Seats\n❄️ Dual-Zone Automatic Climate Control\n🎡 Multifunction Leather Steering Wheel with Paddle Shifters\n🎵 Premium Audio System with Bluetooth, USB & AUX Input\n📷 Reverse Camera with Front & Rear Parking Sensors\n🏎️ Cruise Control & Automatic Headlights with LED DRLs\n🛞 Alloy Wheels & Power Windows/Mirrors",
    engine: '2.0L Turbocharged Inline-4',
    color: 'Grey',
    condition: 'Foreign Used',
    isFeatured: true
  },
  {
    id: 'mini-cooper-countryman-s-2019',
    make: 'MINI',
    model: 'Cooper Countryman S',
    year: 2019,
    price: 28000000,
    mileage: 38000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/1Y5qvg2j/IMG-20260702-WA0012.jpg'
    ],
    description: "✨ 2019 MINI Cooper Countryman S ✨\n🇧🇪 Direct Belgium Import | 📄 Duty Paid | 💎 Mint Condition (Full Option)\n\nThe 2019 MINI Cooper Countryman S is a premium compact SUV that delivers sporty performance, luxury comfort, and distinctive British styling. This Direct Belgium import comes in full-option specification and is in mint condition, making it an excellent choice for buyers seeking a unique luxury crossover with modern technology and premium features.\n\nKey Features:\n⚙️ 2.0L TwinPower Turbo 4-Cylinder Engine\n🏎️ Automatic Transmission\n🔑 Push-Button Start & Keyless Entry\n🪑 Full Leather Interior with Power Front Seats\n☀️ Panoramic Sunroof\n❄️ Dual-Zone Automatic Climate Control\n🎵 MINI Connected Infotainment System with Large Display\n📱 Apple CarPlay, Bluetooth, USB & AUX Ports\n🎧 Premium Sound System\n📷 Reverse Camera with Front & Rear Parking Sensors\n💡 LED Headlights & Daytime Running Lights\n🛞 Alloy Wheels",
    engine: '2.0L TwinPower Turbo 4-Cylinder',
    color: 'Silver',
    condition: 'Direct Belgium',
    isFeatured: true
  },
  {
    id: 'toyota-camry-xse-2019',
    make: 'Toyota',
    model: 'Camry XSE',
    year: 2019,
    price: 28000000,
    mileage: 42000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/qLk6pzSs/IMG-20260727-WA0062.jpg',
      'https://i.ibb.co/Gvpx7hCJ/IMG-20260727-WA0068.jpg',
      'https://i.ibb.co/LM4j63y/IMG-20260727-WA0070.jpg',
      'https://i.ibb.co/cc0DMd89/IMG-20260727-WA0069.jpg',
      'https://i.ibb.co/G4GGB0FD/IMG-20260727-WA0067.jpg'
    ],
    description: "✨ 2019 Toyota Camry XSE ✨\n🌍 Foreign Used | 📄 Custom Duty Paid | 🔑 Keyless Entry\n\nThe 2019 Toyota Camry XSE is a premium sport sedan that combines bold styling, advanced technology, and outstanding reliability. With its aggressive exterior, luxurious interior, and smooth performance, this foreign-used unit is an excellent choice for buyers seeking comfort, style, and long-term dependability.\n\nKey Features:\n⚙️ 2.5L Dynamic Force 4-Cylinder Engine\n🏎️ 8-Speed Automatic Transmission & XSE Sport Trim\n🔑 Keyless Entry with Push-Button Start & Smart Key System\n🪑 Leather-Trimmed Sport Seats with Power Driver & Front Passenger Seats\n❄️ Dual-Zone Automatic Climate Control\n🎡 Multifunction Steering Wheel & Paddle Shifters\n🎵 Touchscreen Infotainment System with Apple CarPlay, Bluetooth & USB\n📷 Reverse Camera & Blind Spot Monitor\n🛣️ Adaptive Cruise Control & Lane Departure Alert\n🛡️ ABS, Traction Control, Vehicle Stability Control & Multiple Airbags",
    engine: '2.5L 4-Cylinder Petrol',
    color: 'Red',
    condition: 'Foreign Used',
    isFeatured: true
  },
  {
    id: 'toyota-camry-se-2013-silver-ng',
    make: 'Toyota',
    model: 'Camry SE',
    year: 2013,
    price: 10900000,
    mileage: 75000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/PvGh48GK/IMG-20260727-WA0040.jpg',
      'https://i.ibb.co/0p2hgj8f/IMG-20260727-WA0074.jpg',
      'https://i.ibb.co/B2NWNR2L/IMG-20260727-WA0077.jpg',
      'https://i.ibb.co/bg52qTdz/IMG-20260727-WA0078.jpg'
    ],
    description: "✨ 2013 Toyota Camry SE ✨\n🇳🇬 Nigerian Used | 📄 Custom Duty Paid | 🌟 Extremely Clean\n\nThe 2013 Toyota Camry SE blends sporty styling, comfort, and Toyota's renowned reliability. This Nigerian-used unit is exceptionally clean, making it an excellent choice for buyers seeking a dependable midsize sedan with premium driving comfort at an affordable price.\n\nKey Features:\n⚙️ 2.5L 4-Cylinder DOHC Engine\n🏎️ Sport (SE) Trim & Sport-Tuned Suspension\n🪑 Fabric Sport Seats\n🎡 Multifunction Steering Wheel with Cruise Control\n🎵 Touchscreen Audio System with Bluetooth, USB & AUX Connectivity\n📷 Reverse Camera\n❄️ Dual-Zone Automatic Climate Control\n🔑 Keyless Entry\n🛞 Alloy Wheels & Fog Lights\n⚡ Power Windows & Mirrors\n🛡️ ABS, Vehicle Stability Control (VSC) & Multiple Airbags",
    engine: '2.5L 4-Cylinder Petrol',
    color: 'Silver',
    condition: 'Nigerian Used',
    isFeatured: true
  },
  {
    id: 'toyota-camry-le-2007',
    make: 'Toyota',
    model: 'Camry LE',
    year: 2007,
    price: 7000000,
    mileage: 95000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/h1YjmC00/IMG-20260727-WA0051.jpg',
      'https://i.ibb.co/TMSPbjGm/IMG-20260727-WA0054.jpg',
      'https://i.ibb.co/Rk2Q06R0/IMG-20260727-WA0056.jpg',
      'https://i.ibb.co/RkFcVDWJ/IMG-20260727-WA0057.jpg',
      'https://i.ibb.co/3YVPNdQ6/IMG-20260727-WA0059.jpg'
    ],
    description: "✨ 2007 Toyota Camry LE ✨\n📄 Duty Paid | 🌟 Extremely Clean\n\nThe 2007 Toyota Camry LE is a reliable and fuel-efficient midsize sedan renowned for its durability, comfort, and low maintenance costs. It's an excellent choice for daily commuting, ride-hailing, family use, or first-time car buyers seeking dependable transportation.\n\nKey Features:\n⚙️ Automatic Transmission\n⛽ 2.4L 4-Cylinder Engine (Fuel Efficient)\n🪑 Fabric Interior\n❄️ Air Conditioning\n🚗 Power Steering\n🪟 Power Windows & Door Locks\n🎡 Multifunction Steering Wheel\n🎵 AM/FM/CD Audio System\n🏎️ Cruise Control\n🛞 Alloy Wheel Covers\n🧳 Spacious Cabin & Large Boot\n🛡️ Dual Front Airbags, ABS & Remote Central Locking\n\nPerformance:\n• Smooth and dependable engine\n• Comfortable suspension for city and highway driving\n• Excellent fuel economy\n• Affordable maintenance with widely available spare parts",
    engine: '2.4L 4-Cylinder Petrol',
    color: 'Silver',
    condition: 'Extremely Clean',
    isFeatured: true
  },
  {
    id: 'toyota-camry-se-2016-white',
    make: 'Toyota',
    model: 'Camry SE',
    year: 2016,
    price: 15700000,
    mileage: 55000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/YBr1zHsR/IMG-20260727-WA0041.jpg',
      'https://i.ibb.co/zT74g4rs/IMG-20260727-WA0044.jpg',
      'https://i.ibb.co/zhndkzkv/IMG-20260727-WA0049.jpg',
      'https://i.ibb.co/7xhHCHZC/IMG-20260727-WA0046.jpg',
      'https://i.ibb.co/mCnrBMkQ/IMG-20260727-WA0047.jpg'
    ],
    description: "✨ 2016 Toyota Camry SE ✨\n🌍 Foreign Used | 📄 Duty Paid | 🤍 Elegant White Exterior\nExperience comfort, reliability, and sporty styling with this 2016 Toyota Camry SE. Designed for everyday driving and long-distance comfort, this sedan offers excellent fuel economy, responsive performance, and Toyota's renowned durability.\n\nKey Features:\n🔑 Keyless Entry\n⚙️ Automatic Transmission\n⛽ Fuel-Efficient Petrol Engine\n🪑 Premium Cloth Interior\n❄️ Chilled Air Conditioning\n🎵 Touchscreen Audio System with Bluetooth, USB & AUX\n📷 Reverse Camera\n🛞 Factory Alloy Wheels\n🛣️ Smooth Suspension & Comfortable Ride\n🧳 Spacious Boot\n🛡️ ABS, Airbags & Vehicle Stability Control",
    engine: '2.5L 4-Cylinder Petrol',
    color: 'White',
    condition: 'Foreign Used',
    isFeatured: true
  },
  {
    id: 'toyota-camry-se-2013-red',
    make: 'Toyota',
    model: 'Camry SE',
    year: 2013,
    price: 11500000,
    mileage: 68000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/bMQ3Jj4P/IMG-20260727-WA0030.jpg',
      'https://i.ibb.co/0ygddzTD/IMG-20260727-WA0033.jpg',
      'https://i.ibb.co/qM1wHf4v/IMG-20260727-WA0037.jpg',
      'https://i.ibb.co/QFN5Dp1k/IMG-20260727-WA0036.jpg'
    ],
    description: "✨ 2013 Toyota Camry SE ✨\n📄 Duty Paid | ☀️ Sunroof | ❤️ Sporty Red Exterior\nEnjoy comfort, style, and Toyota's legendary reliability with this 2013 Toyota Camry SE. This sporty sedan offers a smooth ride, responsive performance, a spacious cabin, and excellent fuel efficiency—making it ideal for both daily commuting and long-distance travel.\n\nKey Features:\n☀️ Factory Sunroof\n🔑 Keyless Entry\n⚙️ Automatic Transmission\n⛽ Petrol Engine\n🪑 Premium Cloth Interior\n❄️ Chilled Air Conditioning\n🎵 AM/FM Audio System with Bluetooth/USB\n🛞 Alloy Wheels\n🛣️ Smooth Suspension & Comfortable Ride\n🧳 Spacious Boot\n🛡️ ABS, Airbags & Stability Control",
    engine: '2.5L 4-Cylinder Petrol',
    color: 'Red',
    condition: 'Extremely Clean',
    isFeatured: true
  },
  {
    id: 'hyundai-elantra-se-2020-white',
    make: 'Hyundai',
    model: 'Elantra SE',
    year: 2020,
    price: 14700000,
    mileage: 45000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/CRLGhK4/IMG-20260706-WA0029.jpg',
      'https://i.ibb.co/zWrTxg3j/IMG-20260706-WA0031.jpg',
      'https://i.ibb.co/rKDcc6R5/IMG-20260706-WA0033.jpg',
      'https://i.ibb.co/GQBVnXss/IMG-20260706-WA0035.jpg',
      'https://i.ibb.co/NgwdLsTY/IMG-20260706-WA0037.jpg'
    ],
    description: '✨ 2020 Hyundai Elantra SE ✨\n🇳🇬 Nigerian Used | 📄 Duty Paid | 🤍 Clean White Exterior\nEnjoy a stylish, comfortable, and fuel-efficient driving experience with this clean 2020 Hyundai Elantra SE. This modern sedan offers sleek styling, a spacious cabin, smooth performance, and excellent everyday practicality.\n🚘 Clean exterior\n🪑 Comfortable and spacious interior\n⚙️ Automatic transmission\n⛽ Petrol engine\n🛣️ Smooth and reliable performance\n🔑 Excellent for city and long-distance driving',
    engine: '2.0L 4-Cylinder Petrol',
    color: 'White',
    condition: 'Nigerian Used',
    isFeatured: true
  },
  {
    id: 'toyota-venza-2010-red',
    make: 'Toyota',
    model: 'Venza',
    year: 2010,
    price: 17800000,
    mileage: 72000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/W4xR5n5F/IMG-20260706-WA0039.jpg',
      'https://i.ibb.co/vSY5HQJ/IMG-20260706-WA0041.jpg',
      'https://i.ibb.co/DPz4pZLN/IMG-20260706-WA0043.jpg',
      'https://i.ibb.co/2p7bCFT/IMG-20260706-WA0045.jpg',
      'https://i.ibb.co/vxsHHCd9/IMG-20260708-WA0030.jpg'
    ],
    description: '✨ 2010 Toyota Venza ✨\n🇺🇸 Foreign Used | 📄 Duty Paid | ❤️ Beautiful Red Exterior\nExperience comfort, reliability, and practicality in this clean Toyota Venza crossover SUV. It offers a spacious cabin, smooth driving experience, stylish design, and the dependable performance Toyota is known for.\n🚘 Clean exterior\n🛞 Comfortable and spacious interior\n⚙️ Automatic transmission\n⛽ Petrol engine\n🛣️ Excellent for city and long-distance driving\n🔑 Reliable Toyota performance',
    engine: '2.7L 4-Cylinder Petrol',
    color: 'Red',
    condition: 'Foreign Used',
    isFeatured: true
  },
  {
    id: 'mercedes-ml350-2015',
    make: 'Mercedes-Benz',
    model: 'ML350 4MATIC',
    year: 2015,
    price: 29000000,
    mileage: 82000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/PGYDnWbz/IMG-20260715-WA0074.jpg?id=7tzk5pTN',
      'https://i.ibb.co/TB8X4FGb/IMG-20260715-WA0076.jpg',
      'https://i.ibb.co/PGYDnWbz/IMG-20260715-WA0074.jpg?id=7tzk5pTN'
    ],
    description: '✨ 2015 Mercedes-Benz ML350 ✨\n🇧🇪 Clean Used | 2026 Duty Paid 🇬🇭\n🔑 Keyless Entry | 🚘 Luxury SUV | 🤍 Elegant Pearl White Exterior\nExperience luxury, comfort, and performance in this beautiful Mercedes-Benz ML350. A stylish and spacious SUV with a premium look, excellent road presence, and the comfort you expect from Mercedes-Benz.',
    engine: '3.5L V6',
    color: 'pearl white',
    condition: 'Clean Used',
    isFeatured: true
  },
  {
    id: 'mercedes-e350-2010',
    make: 'Mercedes-Benz',
    model: 'E350',
    year: 2010,
    price: 9000000,
    mileage: 85000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/FkJp7PT9/IMG-20260720-WA0019.jpg?id=MypdNX0b',
      'https://i.ibb.co/C362cXG2/IMG-20260716-WA0021.jpg',
      'https://i.ibb.co/kVbLptWR/IMG-20260716-WA0036.jpg',
      'https://i.ibb.co/ymLwFgS2/IMG-20260716-WA0038.jpg'
    ],
    description: '✨ 2010 Mercedes-Benz E350 ✨\n🇩🇪 Clean Used | Duty Paid 🇩🇪\n💎 Keyless Entry | 🚘 Luxury Sedan | 🤍 Elegant White Exterior\nExperience luxury, comfort, and performance in this clean Mercedes-Benz E350. Featuring a refined leather interior, wood-trim dashboard and steering wheel, panoramic sunroof, premium alloy wheels, and the comfort and road presence expected from Mercedes-Benz.',
    engine: '3.5L V6',
    color: 'White',
    condition: 'Clean Used',
    isFeatured: true
  },
  {
    id: 'honda-accord-2026',
    make: 'Honda',
    model: 'Accord',
    year: 2026,
    price: 50000000,
    mileage: 5000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/Y7yYc8Py/IMG-20260713-WA0054.jpg?id=SXdWt05d',
      'https://i.ibb.co/Y7mpNZvT/IMG-20260713-WA0056.jpg',
      'https://i.ibb.co/ZRfSc4Tf/IMG-20260713-WA0062.jpg',
      'https://i.ibb.co/k2RCcvvm/IMG-20260713-WA0060.jpg',
      'https://i.ibb.co/xK5JL063/IMG-20260713-WA0058.jpg'
    ],
    description: '✨ 2026 Honda Accord ✨\n🇧🇪 Foreign Used | Original Duty Paid 🇧🇪\n🚘 Just Arrived | 🩶 Elegant Silver Exterior | ⚡ Modern Honda Accord\nExperience modern styling, comfort, and advanced technology in this beautiful 2026 Honda Accord. With its sleek exterior design, refined interior, digital instrument cluster, touchscreen infotainment system, automatic transmission, spacious cabin, and excellent road presence, this Accord is a perfect choice for anyone looking for a fresh, modern sedan.',
    engine: '1.5L Turbo',
    color: 'Silver',
    condition: 'Foreign Used',
    isFeatured: true
  },
  {
    id: 'lexus-is250-2015',
    make: 'Lexus',
    model: 'IS250 F Sport',
    year: 2015,
    price: 15500000,
    mileage: 82000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/K4znhbc/IMG-20260611-WA0043.jpg?id=HwpZ4BL',
      'https://i.ibb.co/BHS9B7Nm/IMG-20260611-WA0050.jpg',
      'https://i.ibb.co/tw9ns3kt/IMG-20260611-WA0048.jpg',
      'https://i.ibb.co/d0XzKGJr/IMG-20260611-WA0049.jpg',
      'https://i.ibb.co/SX8QzFG5/IMG-20260611-WA0051.jpg'
    ],
    description: '✨ 2015 Lexus IS250 F Sport ✨\n🇳🇬 Abuja Used | Duty Paid 🇳🇬\n🏁 F Sport Package | 🩶 Elegant Silver Exterior | 🖤 Premium Black Leather Interior\nExperience luxury, performance, and sporty styling in this clean 2015 Lexus IS250 F Sport. Featuring a powerful 2.5L V6 engine, sporty F Sport design, premium leather interior, sunroof, stylish alloy wheels, and excellent road presence, this Lexus delivers the perfect balance of comfort and performance.',
    engine: '2.5L V6',
    color: 'Silver',
    condition: 'Nigerian Used',
    isFeatured: true
  },
  {
    id: 'lexus-es350-2011',
    make: 'Lexus',
    model: 'ES350',
    year: 2011,
    price: 11500000,
    mileage: 75000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/d0XD8zGN/IMG-20260722-WA0007.jpg',
      'https://i.ibb.co/hx9S0gWw/IMG-20260722-WA0009.jpg',
      'https://i.ibb.co/fz6r5Vfb/IMG-20260722-WA0011.jpg',
      'https://i.ibb.co/NgpwqDKT/IMG-20260722-WA0013.jpg',
      'https://i.ibb.co/ymPHSvFZ/IMG-20260722-WA0016.jpg'
    ],
    description: '✨ 2011 Lexus ES350 ✨\n🇧🇪 Extremely Clean Used | 🇳🇬 2026 Duty Paid\n🔑 Keyless Entry | 💺 Luxury Leather Interior | ❄️ Dual-Zone Climate Control\nExperience premium comfort, reliability, and smooth performance in this exceptionally clean 2011 Lexus ES350. Powered by a refined 3.5L V6 engine paired with an automatic transmission, this luxury sedan delivers a quiet ride, excellent fuel efficiency for its class, and legendary Lexus dependability.',
    engine: '3.5L V6',
    color: 'Dark Grey (Metallic)',
    condition: 'Direct Belgium',
    isFeatured: true
  },
  {
    id: 'hyundai-santa-fe-2014',
    make: 'Hyundai',
    model: 'Santa Fe',
    year: 2014,
    price: 16000000,
    mileage: 68000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    location: 'Nigeria',
    dealership: 'Silver Star Sourcing',
    images: [
      'https://i.ibb.co/MyCc05hW/IMG-20260721-WA0032.jpg',
      'https://i.ibb.co/d4BZZ3Rs/IMG-20260721-WA0034.jpg',
      'https://i.ibb.co/qYYgS83N/IMG-20260721-WA0036.jpg',
      'https://i.ibb.co/DgpJtZRW/IMG-20260721-WA0040.jpg',
      'https://i.ibb.co/zW5pFRR7/IMG-20260721-WA0039.jpg'
    ],
    description: '✨ 2014 Hyundai Santa Fe ✨\n🌍 Foreign Used | Duty Paid 🇳🇬\n🔑 Keyless Entry | 🚙 Luxury SUV | 💎 Elegant Silver Exterior\nExperience comfort, reliability, and performance with this well-maintained 2014 Hyundai Santa Fe. It offers a spacious 7-seater cabin, smooth automatic transmission, excellent fuel efficiency, premium interior, alloy wheels, fog lamps, multifunction steering controls, air conditioning, and ample cargo space—making it an ideal SUV for both family and business use.',
    engine: '3.3L V6',
    color: 'Silver',
    condition: 'Foreign Used',
    isFeatured: true
  },
  {
    id: 'hyundai-azera-2023',
    make: 'Hyundai',
    model: 'Azera (Full Option)',
    year: 2023,
    price: 93000000,
    mileage: 18000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    location: 'Nigeria',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/s96rzXqZ/IMG-20260721-WA0058.jpg',
      'https://i.ibb.co/HDNBxQ5T/IMG-20260721-WA0055.jpg',
      'https://i.ibb.co/3m1Bjp31/IMG-20260721-WA0054.jpg',
      'https://i.ibb.co/MyDmWVP8/IMG-20260721-WA0060.jpg',
      'https://i.ibb.co/NdcNCBwx/IMG-20260721-WA0056.jpg'
    ],
    description: '✨ 2023 Hyundai Azera (Full Option) ✨\n🌍 Foreign Used | Duty Paid 🇳🇬\n🔑 Keyless Entry | 🌅 Full Panoramic Roof | 💎 Premium Grey Exterior\nExperience first-class luxury, advanced technology, and exceptional comfort with this stunning 2023 Hyundai Azera Full Option. Equipped with a powerful yet fuel-efficient engine, premium leather interior, panoramic sunroof, push-to-start ignition, smart keyless entry, large infotainment display, reverse camera, front & rear parking sensors, wireless charging, premium alloy wheels, LED headlights, dual-zone climate control, and advanced driver-assistance features.',
    engine: '2.5L Smartstream',
    color: 'Grey',
    condition: 'Foreign Used',
    isFeatured: true
  },
  {
    id: 'lexus-is350-2014',
    make: 'Lexus',
    model: 'IS350 F Sport',
    year: 2014,
    price: 20000000,
    mileage: 45000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    location: 'Nigeria',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/DgrkkpSL/IMG-20260611-WA0075-1.jpg',
      'https://i.ibb.co/W4sQ7zVP/IMG-20260611-WA0082.jpg',
      'https://i.ibb.co/xq4GrCQL/IMG-20260611-WA0081.jpg',
      'https://i.ibb.co/TqktbKGr/IMG-20260611-WA0085.jpg',
      'https://i.ibb.co/pvrFHp2c/IMG-20260611-WA0083.jpg',
      'https://i.ibb.co/TBsJVjY0/IMG-20260611-WA0084.jpg'
    ],
    description: '✨ 2014 Lexus IS350 F Sport ✨\n🇧🇪 Accident Free | Direct Belgium | Original Custom Duty 🇳🇬\n🔑 Keyless Entry | 🔥 AMG Sound System | 💎 Elegant Deep Blue Exterior\nExperience luxury, power, and sporty performance with this accident-free 2014 Lexus IS350 F Sport. Powered by a responsive 3.5L V6 engine paired with a smooth automatic transmission, this premium sports sedan features a luxurious leather interior, push-to-start ignition, smart keyless entry, premium AMG sound system, reverse camera, parking sensors, LED daytime running lights, alloy wheels, dual-zone climate control, multifunction steering wheel, cruise control, and exceptional driving comfort. A perfect choice for anyone seeking performance, reliability, and executive class.',
    engine: '3.5L V6 Petrol',
    color: 'Deep Blue',
    condition: 'Direct Belgium',
    isFeatured: false
  },
  {
    id: 'toyota-corolla-2004',
    make: 'Toyota',
    model: 'Corolla',
    year: 2004,
    price: 5000000,
    mileage: 120000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    location: 'Nigeria',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/8gnd2pSn/IMG-20260722-WA0020.jpg',
      'https://i.ibb.co/fd4gnQ5y/IMG-20260722-WA0022.jpg',
      'https://i.ibb.co/rRn3fSnX/IMG-20260722-WA0024.jpg',
      'https://i.ibb.co/3mMvFPMz/IMG-20260722-WA0005.jpg',
      'https://i.ibb.co/b53c0SX6/IMG-20260722-WA0026.jpg'
    ],
    description: '✨ 2004 Toyota Corolla ✨\n🇳🇬 Nigeria Used | Duty Paid\n🔑 Reliable Sedan | ⛽ Fuel Efficient | 🖤 Classic Black Exterior\nOwn one of Toyota\'s most dependable sedans with this well-maintained 2004 Toyota Corolla. Renowned for its durability, fuel economy, and low maintenance costs, this sedan features a smooth automatic transmission, comfortable fabric interior, air conditioning, power windows, power steering, central locking, factory audio system, spacious cabin, and a generous boot space. An excellent choice for daily commuting, ride-hailing, or personal use.',
    engine: '1.8L 4-Cylinder Petrol',
    color: 'Black',
    condition: 'Nigerian Used',
    isFeatured: false
  },
  {
    id: 'toyota-camry-se-2013',
    make: 'Toyota',
    model: 'Camry SE',
    year: 2013,
    price: 15000000,
    mileage: 65000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    location: 'Nigeria',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/CKRmpKHL/IMG-20260630-WA0117.jpg',
      'https://i.ibb.co/8wNH6k0/IMG-20260630-WA0119.jpg',
      'https://i.ibb.co/xS4fcb5C/IMG-20260630-WA0121.jpg',
      'https://i.ibb.co/1GrPJS5Q/IMG-20260630-WA0124.jpg',
      'https://i.ibb.co/mVmnY14D/IMG-20260630-WA0126.jpg',
      'https://i.ibb.co/rGBttmMg/IMG-20260630-WA0128.jpg'
    ],
    description: '✨ 2013 Toyota Camry SE ✨\n🌍 Foreign Used | Duty Paid 🇳🇬\n🔑 Keyless Entry | 🏁 Sport Edition (SE) | ❤️ Premium Red Exterior\nEnjoy the perfect blend of sporty styling, comfort, and Toyota reliability with this clean 2013 Toyota Camry SE. Powered by a fuel-efficient 2.5L 4-cylinder engine and paired with a smooth automatic transmission, this sedan features a premium fabric interior, smart keyless entry, push-to-start ignition, reverse camera, Bluetooth connectivity, multifunction steering wheel, alloy wheels, cruise control, dual-zone climate control, sport-tuned suspension, LED daytime running lights, and a spacious cabin. An excellent choice for daily driving with impressive performance and low maintenance costs.',
    engine: '2.5L 4-Cylinder Petrol',
    color: 'Red',
    condition: 'Foreign Used',
    isFeatured: false
  },
  {
    id: 'mercedes-c300-2013',
    make: 'Mercedes-Benz',
    model: 'C300 4MATIC',
    year: 2013,
    price: 11000000,
    mileage: 72000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/07J9ctH/IMG-20260721-WA0006.jpg',
      'https://i.ibb.co/mFXGmNjd/IMG-20260721-WA0012.jpg',
      'https://i.ibb.co/cSSYQpDk/IMG-20260721-WA0013.jpg',
      'https://i.ibb.co/0ypVrhpS/IMG-20260721-WA0014.jpg',
      'https://i.ibb.co/350Jt7xK/IMG-20260721-WA0004.jpg'
    ],
    description: '✨ 2013 Mercedes-Benz C300 4MATIC ✨\n🇳🇬 Clean Nigeria Used | Duty Paid\n🔑 Keyless Entry | ⭐ 4MATIC AWD | 💙 Elegant Navy Blue Exterior\nExperience luxury, comfort, and confident performance with this well-maintained 2013 Mercedes-Benz C300 4MATIC. Powered by a 3.5L V6 engine and paired with a smooth automatic transmission, this premium sedan features a luxurious leather interior, push-to-start ignition, smart keyless entry, reverse camera, front & rear parking sensors, multifunction steering wheel, cruise control, dual-zone climate control, premium alloy wheels, LED daytime running lights, Bluetooth connectivity, and Mercedes-Benz\'s renowned 4MATIC all-wheel-drive system for enhanced stability and control.',
    engine: '3.5L V6 Petrol',
    color: 'Navy Blue',
    condition: 'Nigerian Used',
    isFeatured: false
  },
  {
    id: 'mercedes-gle400-2016',
    make: 'Mercedes-Benz',
    model: 'GLE 400 4MATIC',
    year: 2016,
    price: 36000000,
    mileage: 58000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/k2pbVC5N/IMG-20260723-WA0014.jpg',
      'https://i.ibb.co/SDsdP5tg/IMG-20260723-WA0021.jpg',
      'https://i.ibb.co/Cppmh1cc/IMG-20260723-WA0020.jpg',
      'https://i.ibb.co/0Vy9gdJs/IMG-20260723-WA0019.jpg',
      'https://i.ibb.co/4RRZTxMC/IMG-20260723-WA0022.jpg'
    ],
    description: '✨ 2016 Mercedes-Benz GLE 400 4MATIC ✨\n🌍 Foreign Used | Duty Paid 🇳🇬\n🔑 Keyless Entry | 📹 360° Camera | ⭐ 4MATIC AWD | ❤️ Premium Red Exterior\nExperience exceptional luxury, performance, and innovation with this stunning 2016 Mercedes-Benz GLE 400 4MATIC. Powered by a 3.0L Twin-Turbo V6 engine and paired with a smooth automatic transmission, this premium SUV delivers refined power and outstanding comfort. It features 360° surround-view camera, smart keyless entry, push-to-start ignition, premium leather interior, front & rear parking sensors, multifunction steering wheel, cruise control, dual-zone climate control, LED headlights, premium alloy wheels, Bluetooth connectivity, power tailgate, and Mercedes-Benz\'s intelligent 4MATIC all-wheel-drive system for superior handling in all driving conditions.',
    engine: '3.0L Twin-Turbo V6 Petrol',
    color: 'Red',
    condition: 'Foreign Used',
    isFeatured: false
  },
  {
    id: 'lexus-es350-2014',
    make: 'Lexus',
    model: 'ES350',
    year: 2014,
    price: 18500000,
    mileage: 68000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/Q3LkfJmp/IMG-20260713-WA0064.jpg',
      'https://i.ibb.co/tPpntdhn/IMG-20260713-WA0066.jpg',
      'https://i.ibb.co/YFvcRs8r/IMG-20260713-WA0068.jpg',
      'https://i.ibb.co/pryzWvKj/IMG-20260713-WA0070.jpg',
      'https://i.ibb.co/PvqJt47b/IMG-20260713-WA0072.jpg'
    ],
    description: '✨ 2014 Lexus ES350 ✨\n🇧🇪 Direct Belgium | 🇳🇬 Duty Paid\n🔑 Keyless Entry | 🛋️ Premium Leather Interior | 🌡️ Dual-Zone Climate Control\n📱 Bluetooth Connectivity | 📷 Reverse Camera | 💡 LED Daytime Running Lights\n🪑 Power Seats | 🎵 Premium Audio System | 🛞 Alloy Wheels\nExperience luxury, comfort, and legendary Lexus reliability in this elegant 2014 ES350. Powered by a smooth 3.5L V6 engine with automatic transmission, it delivers excellent performance, exceptional ride comfort, low maintenance costs, and outstanding fuel efficiency. A perfect executive sedan for both city driving and long-distance travel.',
    engine: '3.5L V6',
    color: 'Pearl White',
    condition: 'Direct Belgium',
    isFeatured: false
  },
  {
    id: 'toyota-rav4-xle-2022',
    make: 'Toyota',
    model: 'RAV4 XLE AWD',
    year: 2022,
    price: 24500000,
    mileage: 32000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/B5DHscJ1/IMG-20260721-WA0024.jpg',
      'https://i.ibb.co/0ypVrhpS/IMG-20260721-WA0014.jpg',
      'https://i.ibb.co/yF3vTJ8r/IMG-20260721-WA0029.jpg',
      'https://i.ibb.co/twTjws2M/IMG-20260721-WA0028.jpg',
      'https://i.ibb.co/xSJ1kSLw/IMG-20260721-WA0030.jpg',
      'https://i.ibb.co/7tZLX1GB/IMG-20260721-WA0009.jpg'
    ],
    description: '✨ 2022 Toyota RAV4 XLE AWD ✨\n🌍 Foreign Used | 🇳🇬 Duty Paid\n🔑 Smart Keyless Entry | 🚙 All-Wheel Drive (AWD) | 🛡️ Toyota Safety Sense\n📱 Apple CarPlay & Android Auto | 📷 Reverse Camera | 🌡️ Dual-Zone Climate Control\n🪑 Premium Fabric Seats | 🎵 Premium Audio System | 💡 LED Headlights & DRLs | 🛞 Alloy Wheels\nExperience outstanding reliability, comfort, and versatility in this beautiful 2022 Toyota RAV4 XLE AWD. Powered by a fuel-efficient 2.5L engine with automatic transmission, it delivers excellent performance, modern technology, impressive safety features, and the legendary durability Toyota is known for. An ideal SUV for city driving, family use, and long-distance travel.',
    engine: '2.5L 4-Cylinder',
    color: 'Silver',
    condition: 'Foreign Used',
    isFeatured: false
  },
  {
    id: 'toyota-highlander-limited-2018',
    make: 'Toyota',
    model: 'Highlander Limited AWD',
    year: 2018,
    price: 28000000,
    mileage: 48000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/MK5RscW/IMG-20260721-WA0016.jpg',
      'https://i.ibb.co/yms87wR1/IMG-20260721-WA0020.jpg',
      'https://i.ibb.co/jSV2fQ6/IMG-20260721-WA0023.jpg',
      'https://i.ibb.co/RTTdFFQb/IMG-20260721-WA0021.jpg',
      'https://i.ibb.co/21fz4sXX/IMG-20260721-WA0005.jpg'
    ],
    description: '✨ 2018 Toyota Highlander Limited AWD ✨\n🇳🇬 Extremely Clean Abuja Used | 🇳🇬 Duty Paid\n🔑 Smart Keyless Entry | 🚙 All-Wheel Drive (AWD) | 🛋️ Premium Leather Interior\n📱 Bluetooth Connectivity | 📷 Reverse Camera | 🛰️ Navigation System\n🌡️ Tri-Zone Automatic Climate Control | 🪑 Heated & Ventilated Power Seats\n🎵 JBL Premium Audio System | 💡 LED Headlights | 🛞 Alloy Wheels | 🅿️ Front & Rear Parking Sensors\nExperience luxury, space, and Toyota\'s legendary reliability in this exceptionally clean 2018 Toyota Highlander Limited AWD. Powered by a refined 3.5L V6 engine with automatic transmission, it delivers strong performance, a smooth ride, advanced safety features, and outstanding comfort for both family and executive use. A premium SUV built for city driving, highway cruising, and long-distance travel.',
    engine: '3.5L V6',
    color: 'Pearl White',
    condition: 'Nigerian Used',
    isFeatured: false
  },
  {
    id: 'lexus-gs350-fsport-2015',
    make: 'Lexus',
    model: 'GS350 F SPORT',
    year: 2015,
    price: 16500000,
    mileage: 62000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/TDV2yQP3/IMG-20260630-WA0130-1.jpg',
      'https://i.ibb.co/zHxfMm0L/IMG-20260630-WA0132-1.jpg',
      'https://i.ibb.co/jv4tcxYF/IMG-20260630-WA0135-1.jpg',
      'https://i.ibb.co/5X53MJYB/IMG-20260630-WA0137-1.jpg',
      'https://i.ibb.co/23jpPDQS/IMG-20260630-WA0139-1.jpg'
    ],
    description: '✨ 2015 Lexus GS350 F SPORT ✨\n🇳🇬 Slightly Used | 🇳🇬 Original Duty Paid\n🔑 Smart Keyless Entry | 🌞 Sunroof | 🛋️ Premium Leather Interior\n📱 Bluetooth Connectivity | 📷 Reverse Camera | 🛰️ Navigation System\n🪑 Power Memory Seats | 🌡️ Dual-Zone Automatic Climate Control\n🎵 Premium Audio System | 💡 LED Headlights & DRLs | 🛞 F SPORT Alloy Wheels\nExperience premium luxury, sporty performance, and legendary Lexus reliability in this stunning 2015 Lexus GS350 F SPORT. Powered by a responsive 3.5L V6 engine with automatic transmission, it offers exceptional driving dynamics, refined comfort, advanced technology, and low maintenance costs. An ideal executive sedan for drivers who appreciate both performance and elegance.',
    engine: '3.5L V6',
    color: 'Silver',
    condition: 'Nigerian Used',
    isFeatured: false
  },
  {
    id: 'mercedes-e300-2017',
    make: 'Mercedes-Benz',
    model: 'E300',
    year: 2017,
    price: 21500000,
    mileage: 55000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/N2ssTJ4C/IMG-20260721-WA0042.jpg',
      'https://i.ibb.co/ynNxn1mx/IMG-20260721-WA0044.jpg',
      'https://i.ibb.co/S7QqvHKz/IMG-20260721-WA0046.jpg',
      'https://i.ibb.co/spw8MV1v/IMG-20260721-WA0048.jpg',
      'https://i.ibb.co/7JPXK02n/IMG-20260721-WA0050.jpg'
    ],
    description: '✨ 2017 Mercedes-Benz E300 ✨\n🇧🇪 Extremely Clean Used | 2026 Duty Paid 🇳🇬\n🔑 Keyless Entry | 🚘 Luxury Sedan | 🤍 Elegant Silver Metallic Exterior\nExperience luxury, comfort, and advanced German engineering with this stunning 2017 Mercedes-Benz E300. It offers a refined driving experience, premium interior, smooth 9-speed automatic transmission, and excellent fuel efficiency. Perfect for anyone seeking style, reliability, and executive-class comfort.',
    engine: '2.0L Turbocharged Inline-4',
    color: 'Silver Metallic',
    condition: 'Direct Belgium',
    isFeatured: false
  },
  {
    id: 'mercedes-c300-2013-white',
    make: 'Mercedes-Benz',
    model: 'C300',
    year: 2013,
    price: 14500000,
    mileage: 65000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/S7vhrtxf/IMG-20260716-WA0039.jpg',
      'https://i.ibb.co/vC8pLGhL/IMG-20260723-WA0050.jpg',
      'https://i.ibb.co/3mJc8W0D/IMG-20260723-WA0049.jpg',
      'https://i.ibb.co/xKt7wFgB/IMG-20260716-WA0042.jpg',
      'https://i.ibb.co/LdzT376r/IMG-20260723-WA0051.jpg',
      'https://i.ibb.co/qMLvBmrv/IMG-20260716-WA0045.jpg'
    ],
    description: '✨ 2013 Mercedes-Benz C300 ✨\n🇺🇸 Foreign Used | 🇳🇬 Duty Paid\n🖤 Black Engine | 🚘 Luxury Sedan | 🤍 Elegant White Exterior\nExperience luxury, comfort, and performance in this beautiful 2013 Mercedes-Benz C300. A stylish and well-equipped luxury sedan with a premium look, smooth automatic transmission, powerful 3.5L V6 petrol engine, and the comfort you expect from Mercedes-Benz.',
    engine: '3.5L V6',
    color: 'White',
    condition: 'Foreign Used',
    isFeatured: false
  },
  {
    id: 'toyota-sienna-2012',
    make: 'Toyota',
    model: 'Sienna',
    year: 2012,
    price: 11000000,
    mileage: 78000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Minivan',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/cc28rJSw/IMG-20260713-WA0083.jpg',
      'https://i.ibb.co/X0t5TPJ/IMG-20260713-WA0085.jpg',
      'https://i.ibb.co/WNs8FTxp/IMG-20260713-WA0087.jpg',
      'https://i.ibb.co/4gSFXZvg/IMG-20260713-WA0082.jpg',
      'https://i.ibb.co/6Rsj91c7/IMG-20260713-WA0080.jpg'
    ],
    description: '✨ 2012 Toyota Sienna ✨\n🇳🇬 Abuja Used | 📄 Duty Paid\n🩶 Elegant Silver Exterior | 🚐 Spacious Family Minivan\nExperience comfort, reliability, and practicality in this extremely clean 2012 Toyota Sienna. A spacious and comfortable family vehicle with a powerful 3.5L V6 petrol engine, smooth automatic transmission, and excellent road presence.',
    engine: '3.5L V6',
    color: 'Silver',
    condition: 'Nigerian Used',
    isFeatured: false
  },
  {
    id: 'toyota-highlander-2011-wine',
    make: 'Toyota',
    model: 'Highlander',
    year: 2011,
    price: 13000000,
    mileage: 85000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/75drH12/IMG-20260724-WA0045.jpg',
      'https://i.ibb.co/vCq41ms1/IMG-20260724-WA0041.jpg',
      'https://i.ibb.co/Jw2C5Jwh/IMG-20260724-WA0043.jpg',
      'https://i.ibb.co/zWMBrtV7/IMG-20260724-WA0046.jpg',
      'https://i.ibb.co/99bzKxz4/IMG-20260724-WA0048.jpg',
      'https://i.ibb.co/QFhsPtG6/IMG-20260724-WA0049.jpg'
    ],
    description: '✨ 2011 Toyota Highlander ✨\n🇳🇬 Duty Paid | ⭐ Full Option\n🔑 Keyless Entry | 🌞 Sunroof | 🍷 Elegant Wine Exterior\nExperience comfort, reliability, and premium utility in this extremely clean 2011 Toyota Highlander. A stylish and spacious SUV with a powerful 3.5L V6 petrol engine, smooth automatic transmission, keyless entry, sunroof, and excellent road presence.',
    engine: '3.5L V6',
    color: 'Wine/Burgundy',
    condition: 'Nigerian Used',
    isFeatured: false
  },
  {
    id: 'hyundai-sonata-2015-grey',
    make: 'Hyundai',
    model: 'Sonata',
    year: 2015,
    price: 13800000,
    mileage: 65000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/MD8P10rH/IMG-20260630-WA0142.jpg',
      'https://i.ibb.co/hFMVyx2S/IMG-20260630-WA0144.jpg',
      'https://i.ibb.co/5gkrFhXv/IMG-20260630-WA0146.jpg',
      'https://i.ibb.co/Hfcbtfhh/IMG-20260630-WA0148.jpg',
      'https://i.ibb.co/RGLtGzzf/IMG-20260630-WA0150.jpg'
    ],
    description: '✨ 2015 Hyundai Sonata ✨\n🇧🇪 Direct Belgium | 🇳🇬 Duty Paid\n🩶 Elegant Grey Exterior | 🚘 Luxury Sedan\nExperience style, comfort, and smooth performance in this 2015 Hyundai Sonata, directly imported from Belgium and fully duty paid. A stylish and spacious sedan with a smooth automatic transmission, efficient petrol engine, premium interior comfort, and excellent road presence.',
    engine: '2.4L 4-Cylinder',
    color: 'Grey',
    condition: 'Direct Belgium',
    isFeatured: false
  },
  {
    id: 'toyota-sienna-2003-silver',
    make: 'Toyota',
    model: 'Sienna',
    year: 2003,
    price: 4500000,
    mileage: 120000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Minivan',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/s96tpdHF/IMG-20260725-WA0003.jpg',
      'https://i.ibb.co/Z1zjZ9k1/IMG-20260725-WA0008.jpg',
      'https://i.ibb.co/1JJSb2HY/IMG-20260725-WA0010.jpg',
      'https://i.ibb.co/bM5GKLGv/IMG-20260725-WA0011.jpg',
      'https://i.ibb.co/TXcP108/IMG-20260725-WA0009.jpg'
    ],
    description: '✨ 2003 Toyota Sienna ✨\n🇳🇬 Duty Paid | 🩶 Elegant Silver Exterior\n🚐 Spacious Family Minivan | ⚙️ Reliable V6 Performance\nExperience comfort, practicality, and reliability in this clean used 2003 Toyota Sienna. A spacious family minivan powered by a reliable 3.0L V6 petrol engine, with automatic transmission and excellent practicality for everyday use and family trips.',
    engine: '3.0L V6',
    color: 'Silver',
    condition: 'Nigerian Used',
    isFeatured: false
  },
  {
    id: 'lexus-es350-2016-black',
    make: 'Lexus',
    model: 'ES 350',
    year: 2016,
    price: 26000000,
    mileage: 58000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/6JcvjM6V/IMG-20260725-WA0013.jpg',
      'https://i.ibb.co/B5QZh8gJ/IMG-20260725-WA0017.jpg',
      'https://i.ibb.co/P7D3S3C/IMG-20260725-WA0016.jpg',
      'https://i.ibb.co/4nTydxQs/IMG-20260725-WA0019.jpg'
    ],
    description: '✨ 2016 Lexus ES 350 ✨\n🇯🇵 Foreign Used | Tincan Cleared 🇳🇬\n🔑 Keyless Entry | 🚘 Luxury Sedan | 🖤 Elegant Black Exterior\nExperience luxury, comfort, and legendary Lexus reliability with this stunning 2016 Lexus ES 350. Powered by a refined 3.5L V6 engine, this executive sedan delivers smooth performance, premium comfort, and outstanding durability, making it the perfect choice for both city driving and long-distance travel.',
    engine: '3.5L V6',
    color: 'Black',
    condition: 'Foreign Used',
    isFeatured: false
  },
  {
    id: 'lexus-is250-2015-white',
    make: 'Lexus',
    model: 'IS 250 AWD',
    year: 2015,
    price: 16500000,
    mileage: 62000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/y9sqPLY/IMG-20260703-WA0024.jpg',
      'https://i.ibb.co/mCWDLYGt/IMG-20260703-WA0022.jpg',
      'https://i.ibb.co/9mnK8Y4f/IMG-20260703-WA0020.jpg',
      'https://i.ibb.co/rKJNdhzk/IMG-20260725-WA0021.jpg',
      'https://i.ibb.co/FL5Ttvck/IMG-20260703-WA0019.jpg'
    ],
    description: '✨ 2015 Lexus IS 250 AWD ✨\n🇳🇬 Abuja Used | Just Like Tokunbo | 2026 Duty Paid 🇳🇬\n🔑 Keyless Entry | 🚘 Luxury Sports Sedan | 🤍 Elegant Pearl White Exterior\n\nFeatures:\n• All-Wheel Drive (AWD)\n• Smart Keyless Entry & Push Start\n• Premium Leather Interior\n• Reverse Camera & Bluetooth Connectivity\n• Dual-Zone Climate Control & Power Front Seats\n• Alloy Wheels & LED Daytime Running Lights\n• Parking Sensors, ABS & Multiple Airbags',
    engine: '2.5L V6',
    color: 'Pearl White',
    condition: 'Nigerian Used',
    isFeatured: false
  },
  {
    id: 'hyundai-i30-gt-2015-black',
    make: 'Hyundai',
    model: 'i30 GT',
    year: 2015,
    price: 15000000,
    mileage: 55000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Hatchback',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/n8BDCZn6/IMG-20260703-WA0021.jpg',
      'https://i.ibb.co/Q7HxRrpp/IMG-20260725-WA0026.jpg',
      'https://i.ibb.co/gZkzdBhy/IMG-20260725-WA0028.jpg',
      'https://i.ibb.co/ZbS9Pqp/IMG-20260725-WA0029.jpg',
      'https://i.ibb.co/vvMWVqQ7/IMG-20260725-WA0027.jpg'
    ],
    description: '✨ 2015 Hyundai i30 GT ✨\n🇧🇪 Foreign Used | 2026 Duty Paid 🇳🇬\n🔑 Keyless Entry & Push Start | 🚗 Hatchback | 🖤 Elegant Black Exterior\n\nExperience sporty performance, practicality, and excellent fuel efficiency with this 2015 Hyundai i30 GT. This well-maintained hatchback offers a comfortable cabin, smooth automatic transmission, 2.0L Inline-4 engine, and modern features making it ideal for daily commuting and long-distance travel.\n\nFeatures:\n• Keyless Entry & Push Start Button\n• Bluetooth Connectivity & Reverse Camera\n• Premium Interior & Multifunction Steering Wheel\n• Cruise Control & Automatic Climate Control\n• Alloy Wheels & LED Daytime Running Lights\n• Front Fog Lamps, ABS, ESC & Multiple Airbags',
    engine: '2.0L Inline-4',
    color: 'Black',
    condition: 'Foreign Used',
    isFeatured: false
  },
  {
    id: 'toyota-sienna-2009-blue',
    make: 'Toyota',
    model: 'Sienna XLE Limited',
    year: 2009,
    price: 12500000,
    mileage: 72000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Minivan',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/XfyP7xyK/IMG-20260725-WA0031.jpg',
      'https://i.ibb.co/Vcz0Y1QV/IMG-20260725-WA0035.jpg',
      'https://i.ibb.co/CptJb0bp/IMG-20260725-WA0038.jpg',
      'https://i.ibb.co/4g2yQwSw/IMG-20260725-WA0039.jpg',
      'https://i.ibb.co/Y4q6fvXq/IMG-20260725-WA0034.jpg'
    ],
    description: '✨ 2009 Toyota Sienna XLE Limited ✨\n🇧🇪 Foreign Used | 2026 Duty Paid 🇳🇬\n🔑 Keyless Entry & Push Start | 🚐 Premium Minivan | 💙 Elegant Blue Exterior\n\nExperience unmatched comfort, reliability, and spaciousness with this 2009 Toyota Sienna XLE Limited. Designed for families and long-distance travel, this premium minivan offers a smooth ride, powerful 3.5L V6 engine, and Toyota\'s legendary durability.\n\nFeatures:\n• XLE Limited Trim\n• Smart Keyless Entry & Push Start Button\n• Premium Leather Interior & Power Sliding Doors\n• Power Tailgate & Reverse Camera\n• Tri-Zone Automatic Climate Control\n• Power Front Seats, Cruise Control & Alloy Wheels\n• Roof Rails, ABS, Vehicle Stability Control & Multiple Airbags',
    engine: '3.5L V6',
    color: 'Blue',
    condition: 'Foreign Used',
    isFeatured: false
  },
  {
    id: 'toyota-corolla-2015-white',
    make: 'Toyota',
    model: 'Corolla LE',
    year: 2015,
    price: 14500000,
    mileage: 68000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/mCsfcP3n/IMG-20260725-WA0041.jpg',
      'https://i.ibb.co/QFY2Bd8L/IMG-20260725-WA0043.jpg',
      'https://i.ibb.co/q3R9z3w3/IMG-20260725-WA0047.jpg',
      'https://i.ibb.co/YTT457jr/IMG-20260725-WA0049.jpg',
      'https://i.ibb.co/PvqKqsPt/IMG-20260725-WA0045.jpg'
    ],
    description: '✨ 2015 Toyota Corolla LE ✨\n🇧🇪 Foreign Used | Original 2026 Duty Paid 🇳🇬\n🔑 Keyless Entry & Push Start | 🚗 Sedan | 🤍 Elegant Pearl White Exterior\n\nExperience comfort, reliability, and exceptional fuel economy with this 2015 Toyota Corolla LE. This foreign-used sedan has original 2026 duty paid and is in excellent condition. Renowned for its durability, low maintenance costs, and smooth driving experience, it\'s an ideal choice for both personal and commercial use.\n\nFeatures:\n• Keyless Entry & Push Start Button\n• Reverse Camera & Bluetooth Connectivity\n• Touchscreen Multimedia System & Premium Fabric Interior\n• Multifunction Steering Wheel & Cruise Control\n• Automatic Climate Control & Alloy Wheels\n• LED Daytime Running Lights, Power Windows & Power Mirrors\n• ABS, Vehicle Stability Control & Multiple Airbags',
    engine: '1.8L Inline-4',
    color: 'Pearl White',
    condition: 'Foreign Used',
    isFeatured: false
  },
  {
    id: 'honda-accord-2016-grey',
    make: 'Honda',
    model: 'Accord',
    year: 2016,
    price: 13500000,
    mileage: 60000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/d0n8bcng/IMG-20260725-WA0078.jpg',
      'https://i.ibb.co/9mk7r1KF/IMG-20260725-WA0077.jpg',
      'https://i.ibb.co/HfhhyBcL/IMG-20260725-WA0091.jpg',
      'https://i.ibb.co/bgMdLmpg/IMG-20260725-WA0087.jpg',
      'https://i.ibb.co/d0YVRmKB/IMG-20260725-WA0071.jpg',
      'https://i.ibb.co/prKHXqKL/IMG-20260725-WA0072.jpg'
    ],
    description: '✨ 2016 Honda Accord ✨\n🇳🇬 Abuja Used | Duty Paid 📄\n🔑 Keyless Entry | 📱 Double Screen | 🌞 Sunroof | 🩶 Elegant Dark Grey Exterior\n\nExperience style, comfort, and performance in this extremely clean 2016 Honda Accord. A premium and spacious sedan featuring keyless entry, double-screen infotainment system, sunroof, smooth automatic transmission, 2.4L 4-Cylinder engine, and excellent road presence.',
    engine: '2.4L 4-Cylinder',
    color: 'Dark Grey',
    condition: 'Nigerian Used',
    isFeatured: false
  },
  {
    id: 'lexus-nx300-2020-grey',
    make: 'Lexus',
    model: 'NX 300',
    year: 2020,
    price: 35500000,
    mileage: 45000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/PZB7fXWr/IMG-20260725-WA0107.jpg',
      'https://i.ibb.co/4nZz9pm3/IMG-20260725-WA0109.jpg',
      'https://i.ibb.co/39M2Qb70/IMG-20260725-WA0102.jpg',
      'https://i.ibb.co/fVTQ9b7J/IMG-20260725-WA0108.jpg'
    ],
    description: '✨ 2020 Lexus NX300 ✨\n🇳🇬 Abuja Used | Clean Used | Duty Paid 📄\n🩶 Elegant Grey Exterior | 🚘 Luxury SUV\n\nExperience luxury, comfort, and performance in this clean 2020 Lexus NX300. A stylish and premium SUV featuring a powerful 2.0L turbocharged petrol engine, smooth automatic transmission, modern styling, excellent road presence, and the comfort and refinement expected from Lexus.',
    engine: '2.0L Turbo 4-Cylinder',
    color: 'Grey',
    condition: 'Nigerian Used',
    isFeatured: false
  },
  {
    id: 'toyota-camry-2022-black',
    make: 'Toyota',
    model: 'Camry XSE',
    year: 2022,
    price: 43500000,
    mileage: 38000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/pB9rW5qn/IMG-20260725-WA0051.jpg',
      'https://i.ibb.co/2rktpbh/IMG-20260725-WA0053.jpg',
      'https://i.ibb.co/m584Nm2m/IMG-20260725-WA0059.jpg',
      'https://i.ibb.co/LXV08cQM/IMG-20260725-WA0058.jpg',
      'https://i.ibb.co/s9tnsHnd/IMG-20260725-WA0056.jpg'
    ],
    description: '✨ 2022 Toyota Camry XSE ✨\n🇧🇪 Direct Belgium Import | Foreign Used | Original Duty Paid (July 18, 2026) 📄\n⭐ Full Option | 🌞 Panoramic Roof | 🔑 Keyless Entry | 📉 Low Mileage | 🖤 Elegant Black Exterior\n\nExperience premium comfort, style, and performance in this 2022 Toyota Camry XSE, directly imported from Belgium. This full-option luxury sedan features a panoramic roof, keyless entry, low mileage, sporty XSE styling, 2.5L 4-Cylinder engine, and excellent road presence.',
    engine: '2.5L 4-Cylinder',
    color: 'Black',
    condition: 'Foreign Used',
    isFeatured: false
  },
  {
    id: 'toyota-4runner-2015-black',
    make: 'Toyota',
    model: '4Runner',
    year: 2015,
    price: 40800000,
    mileage: 52000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/JRybQDBL/IMG-20260724-WA0029-2.jpg',
      'https://i.ibb.co/B27TjDQx/IMG-20260724-WA0031-1.jpg',
      'https://i.ibb.co/YFX6RnjB/IMG-20260724-WA0033-1.jpg',
      'https://i.ibb.co/pr2CV6PR/IMG-20260724-WA0035-1.jpg',
      'https://i.ibb.co/TD2CyYRb/IMG-20260724-WA0037-1.jpg'
    ],
    description: '✨ 2015 Toyota 4Runner ✨\n🌍 Foreign Used | 📄 Duty Fully Paid 🇳🇬\n🖤 Elegant Black Exterior | 🚘 Rugged Luxury SUV | ⚡ Powerful V6 Performance\n\nExperience rugged capability, comfort, and reliability in this 2015 Toyota 4Runner. A powerful and spacious SUV featuring a 4.0L V6 petrol engine, smooth automatic transmission, excellent ground clearance, strong road presence, and the durability Toyota 4Runner is known for.',
    engine: '4.0L V6',
    color: 'Black',
    condition: 'Foreign Used',
    isFeatured: false
  },
  {
    id: 'honda-accord-2023-black',
    make: 'Honda',
    model: 'Accord',
    year: 2023,
    price: 43600000,
    mileage: 32000,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    location: 'Abuja',
    dealership: 'Coscharis Certified Sourcing',
    images: [
      'https://i.ibb.co/3m7VRZYk/IMG-20260716-WA0029.jpg',
      'https://i.ibb.co/C3TxS9LW/IMG-20260716-WA0019.jpg',
      'https://i.ibb.co/vG8KmtT/IMG-20260716-WA0020.jpg',
      'https://i.ibb.co/tpvbqm7t/IMG-20260716-WA0031.jpg',
      'https://i.ibb.co/ZzdTbSXh/IMG-20260716-WA0033.jpg'
    ],
    description: '✨ 2023 Honda Accord ✨\n🌍 Foreign Used | 📄 Duty Paid 🇳🇬\n🖤 Elegant Black Exterior | 🚘 Modern Luxury Sedan\n\nExperience modern luxury, comfort, and performance in this 2023 Honda Accord. A stylish and spacious sedan with a smooth automatic transmission, efficient turbocharged petrol engine, refined interior, modern design, and excellent road presence.',
    engine: '1.5L Turbo 4-Cylinder',
    color: 'Black',
    condition: 'Foreign Used',
    isFeatured: false
  }
];

export const HOW_IT_WORKS_STEPS = [
  {
    number: '01',
    title: 'Consultation & Discovery',
    description: 'Share your vehicle needs, budget range, and lifestyle preferences. Our specialist guides you through optimal options.'
  },
  {
    number: '02',
    title: 'Tailored Vehicle Sourcing',
    description: 'We scour our network of top verified dealerships across Nigeria to find cars that match your exact criteria.'
  },
  {
    number: '03',
    title: 'Rigorous Inspection & Dealership Matching',
    description: 'Every car undergoes a detailed inspection to confirm electrical, mechanical, and documentation status.'
  },
  {
    number: '04',
    title: 'Seamless Safe Purchase',
    description: 'We assist with comparison, vehicle test-drives, secure payments, and transfer documents, complete with commission options.'
  }
];

export const TRUST_REASONS = [
  {
    title: 'Deals with Multiple Dealerships',
    description: 'We are not tied to a single lot. We compare vehicles across multiple top dealerships to get you the absolute best quality and value.'
  },
  {
    title: 'Personalized Sourcing',
    description: 'Tell us what you want and we find it—even if it is not currently on our lists. No stressful dealer hunting.'
  },
  {
    title: 'Independent Inspection',
    description: 'We act strictly in your interest. We inspect vehicle history, mechanical integrity, and ownership status before you pay a dime.'
  },
  {
    title: 'Comprehensive Guidance',
    description: 'From choosing the model to paper registration and delivery, a dedicated consultant handles the heavy lifting.'
  },
  {
    title: '24/7 WhatsApp & Phone Support',
    description: 'Instantly talk to real experts at any stage. Direct chat, quick responses, and no automated telephone queues.'
  }
];
